---
name: Examen Mega Programadores 2019 - 3er año
locale: es
type: learning
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 9
- 1
- 2
- 3
- 10
- 11
- 4
- 5
private: false
